"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-15 17:22:32.569000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plex_library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("original_title", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "movie", "series", "anime", "cartoon", "ignore", name="categoryenum"
            ),
            nullable=False,
        ),
        sa.Column("genre_ids", sa.JSON(), nullable=True),
        sa.Column("collections", sa.JSON(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("anilist_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("collection_name", sa.String(), nullable=True),
        sa.Column("poster_url", sa.String(), nullable=True),
        sa.Column("rating_key", sa.String(), nullable=True),
        sa.Column(
            "added_date", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plex_library_anilist_id"), "plex_library", ["anilist_id"], unique=False
    )
    op.create_index(
        op.f("ix_plex_library_category"), "plex_library", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_plex_library_collection_id"),
        "plex_library",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plex_library_id"), "plex_library", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_plex_library_imdb_id"), "plex_library", ["imdb_id"], unique=False
    )
    op.create_index(
        op.f("ix_plex_library_rating_key"),
        "plex_library",
        ["rating_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plex_library_tmdb_id"), "plex_library", ["tmdb_id"], unique=False
    )
    op.create_index(
        op.f("ix_plex_library_tvdb_id"), "plex_library", ["tvdb_id"], unique=False
    )

    op.create_table(
        "tautulli_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("media_id", sa.String(), nullable=False),
        sa.Column("watch_count", sa.Integer(), nullable=True),
        sa.Column("percent_complete", sa.Float(), nullable=True),
        sa.Column("last_watched", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tautulli_stats_id"), "tautulli_stats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tautulli_stats_media_id"),
        "tautulli_stats",
        ["media_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tautulli_stats_user_id"),
        "tautulli_stats",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "external_classics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("original_title", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "movie", "series", "anime", "cartoon", "ignore", name="categoryenum"
            ),
            nullable=False,
        ),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("anilist_id", sa.Integer(), nullable=True),
        sa.Column("source_api", sa.String(), nullable=False),
        sa.Column("source_list", sa.String(), nullable=True),
        sa.Column("score_external", sa.Float(), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.Column("poster_url", sa.String(), nullable=True),
        sa.Column(
            "last_synced",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
        sa.Column("is_recommended", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_classics_anilist_id"),
        "external_classics",
        ["anilist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_classics_category"),
        "external_classics",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_classics_id"),
        "external_classics",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_classics_source_api"),
        "external_classics",
        ["source_api"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_classics_tmdb_id"),
        "external_classics",
        ["tmdb_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_classics_tvdb_id"),
        "external_classics",
        ["tvdb_id"],
        unique=False,
    )

    op.create_table(
        "sonarr_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sonarr_queue_external_id"),
        "sonarr_queue",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sonarr_queue_id"), "sonarr_queue", ["id"], unique=False
    )

    op.create_table(
        "radarr_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_radarr_queue_external_id"),
        "radarr_queue",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radarr_queue_id"), "radarr_queue", ["id"], unique=False
    )

    op.create_table(
        "wishlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "movie", "series", "anime", "cartoon", "ignore", name="categoryenum"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("poster_url", sa.String(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "external_id", "category", name="uq_wishlist_external_id_category"
        ),
    )
    op.create_index(
        op.f("ix_wishlist_external_id"), "wishlist", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_wishlist_id"), "wishlist", ["id"], unique=False
    )

    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(
        op.f("ix_app_settings_key"), "app_settings", ["key"], unique=True
    )

    op.create_table(
        "task_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_task_status_task_id"), "task_status", ["task_id"], unique=True
    )

    op.create_table(
        "plex_library_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_key", sa.String(), nullable=False),
        sa.Column("library_name", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "movie", "series", "anime", "cartoon", "ignore", name="categoryenum"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plex_library_mappings")
    op.drop_index(op.f("ix_task_status_task_id"), table_name="task_status")
    op.drop_table("task_status")
    op.drop_index(op.f("ix_app_settings_key"), table_name="app_settings")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_wishlist_id"), table_name="wishlist")
    op.drop_index(op.f("ix_wishlist_external_id"), table_name="wishlist")
    op.drop_table("wishlist")
    op.drop_index(op.f("ix_radarr_queue_id"), table_name="radarr_queue")
    op.drop_index(op.f("ix_radarr_queue_external_id"), table_name="radarr_queue")
    op.drop_table("radarr_queue")
    op.drop_index(op.f("ix_sonarr_queue_id"), table_name="sonarr_queue")
    op.drop_index(op.f("ix_sonarr_queue_external_id"), table_name="sonarr_queue")
    op.drop_table("sonarr_queue")
    op.drop_index(op.f("ix_external_classics_tvdb_id"), table_name="external_classics")
    op.drop_index(op.f("ix_external_classics_tmdb_id"), table_name="external_classics")
    op.drop_index(
        op.f("ix_external_classics_source_api"), table_name="external_classics"
    )
    op.drop_index(op.f("ix_external_classics_id"), table_name="external_classics")
    op.drop_index(
        op.f("ix_external_classics_category"), table_name="external_classics"
    )
    op.drop_index(
        op.f("ix_external_classics_anilist_id"), table_name="external_classics"
    )
    op.drop_table("external_classics")
    op.drop_index(op.f("ix_tautulli_stats_user_id"), table_name="tautulli_stats")
    op.drop_index(op.f("ix_tautulli_stats_media_id"), table_name="tautulli_stats")
    op.drop_index(op.f("ix_tautulli_stats_id"), table_name="tautulli_stats")
    op.drop_table("tautulli_stats")
    op.drop_index(op.f("ix_plex_library_tvdb_id"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_tmdb_id"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_rating_key"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_imdb_id"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_id"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_collection_id"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_category"), table_name="plex_library")
    op.drop_index(op.f("ix_plex_library_anilist_id"), table_name="plex_library")
    op.drop_table("plex_library")
    op.execute("DROP TYPE IF EXISTS categoryenum")
    # ### end Alembic commands ###
